name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate community feedback to improve the game.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - Gameplay Feature (new game modes, rules, mechanics)
        - UI/UX Improvement (better interface, accessibility)
        - Social Feature (chat, reactions, profiles)
        - Card Management (new card packs, custom cards)
        - Performance/Technical (speed, reliability)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        Example: I'm always frustrated when... or It would be great if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        Have you thought of other ways to solve this problem?

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Critical (can't play without it)
        - High (would significantly improve experience)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: |
        - Mockups/screenshots
        - Examples from other games
        - Technical considerations

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the spirit of Cards Against Humanity
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
